language: scala
scala:
  - 2.11.8

cache:
directories:
  - $HOME/.m2

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  email: yaooqinn@hotmail.com
  name: Kent Yao
  on:
    branch: master

install:
  - ./build/mvn install -q -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - ./build/mvn package -q -Dmaven.javadoc.skip=true -B -V
  - ./build/mvn package -Pspark-2.2 -q -Dmaven.javadoc.skip=true -B -V
  - ./build/mvn package -Pspark-2.3 -q -Dmaven.javadoc.skip=true -B -V


language: java
after_success:
  - bash <(curl -s https://codecov.io/bash)
